bert:
    atom_vocab_size: 18
    nmr_vocab_size: 1801
    embed_dim: 256
    ffn_dim: 512
    head: 4
    encoder_layers: 6
    p: 0.1

train:
    batch_size: 8
    num_workers: 4
    AdamW:
        lr: 1.0e-04
        beta1: 0.9
        beta2: 0.999
        eps: 1.0e-08
    epochs: 30
dataset:
    dataset_path: /home/zjh/mr/downstream/dataset/bace.pth
    mol_fix_len: 256
    num_workers: 4
    split: [8,1,1]
    stratify:
task_type: "classify"
device: cuda:1
pretrain_model_path:
model_save_path: /home/zjh/mr/res/bace.pth
log_path: /home/zjh/mr/res/bace.log
res_path: /home/zjh/mr/res/bace.csv
seed: 42
nmr: False
pos: False